---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.prefix }}-front-end"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.prefix }}-front-end"
  template:
    metadata:
      labels:
        app: "{{ .Values.prefix }}-front-end"
    spec:
      affinity:
        podAntiAffinity: # Make sure servers aren't scheduled on same node
          preferredDuringSchedulingIgnoredDuringExecution: # Set to 'preferred' just in case we have a single-node cluster
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: "{{ .Values.prefix }}-front-end"
              topologyKey: kubernetes.io/hostname
      containers:
        - name: "{{ .Values.prefix }}-front-end"
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          env:
            - name: S3_ENDPOINT
              value: "{{ .Values.s3Endpoint }}"
            - name: S3_ENDPOINT_PORT
              value: "{{ .Values.s3EndpointPort }}"
            - name: ACCESS_KEY
              value: "{{ .Values.accessKey }}"
            - name: SECRET_KEY
              value: "{{ .Values.secretKey }}"
            - name: BUCKET_NAME
              value: "{{ .Values.bucketName }}"
            - name: USE_SSL
              value: "true"
            - name: NODE_TLS_REJECT_UNAUTHORIZED # Disables SSL certificate validation (same as mc --insecure)
              value: "0"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.prefix }}-front-end"
  labels:
    app: "{{ .Values.prefix }}-front-end"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: "{{ .Values.prefix }}-front-end"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.prefix }}-cloudflared"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.prefix }}-cloudflared"
  template:
    metadata:
      labels:
        app: "{{ .Values.prefix }}-cloudflared"
    spec:
      affinity:
        podAntiAffinity: # Make sure servers aren't scheduled on same node
          preferredDuringSchedulingIgnoredDuringExecution: # Set to 'preferred' just in case we have a single-node cluster
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: "{{ .Values.prefix }}-cloudflared"
              topologyKey: kubernetes.io/hostname
      containers:
        - name: "{{ .Values.prefix }}-cloudflared"
          image: cloudflare/cloudflared:2025.4.0
          imagePullPolicy: Always
          command: ["cloudflared", "tunnel", "--no-autoupdate", "run", "--token", "$(CF_TOKEN)"]
          env:
          - name: CF_TOKEN
            value: "{{ .Values.cfToken }}"
